driver:
  name: dokken
  chef_version: latest
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: debian-11
  driver:
    image: debian:11
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y lsb-release net-tools

- name: debian-12
  driver:
    image: debian:12
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y lsb-release net-tools

- name: ubuntu-20.04
  driver:
    image: ubuntu:20.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y net-tools

- name: ubuntu-22.04
  driver:
    image: ubuntu:22.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y net-tools

- name: rockylinux-8
  driver:
    image: rockylinux:8
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install which net-tools

- name: rockylinux-9
  driver:
    image: rockylinux:9
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install which net-tools

suites:
  - name: config
    run_list:
      - recipe[vagrant_example::default]
