name 'vagrant_example'
maintainer 'Thomas Vincent'
maintainer_email 'thomasvincent@gmail.com'
license 'Apache-2.0'
description 'Example Chef cookbook demonstrating Apache2 installation and vhost configuration'
version '2.0.0'
chef_version '>= 18.0'

supports 'ubuntu', '>= 20.04'
supports 'debian', '>= 11.0'
supports 'redhat', '>= 7.0'
supports 'rocky', '>= 8.0'
supports 'centos', '>= 7.0'
supports 'amazon', '>= 2.0'

source_url 'https://github.com/thomasvincent/chef-vagrant-example'
issues_url 'https://github.com/thomasvincent/chef-vagrant-example/issues'
