name: Windows CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  windows-test:
    name: Windows Integration Tests
    runs-on: windows-latest
    strategy:
      matrix:
        os: ["windows-2019", "windows-2022"]
        scenario: ["default", "packages"]
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Install Chef
        shell: powershell
        run: |
          . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -channel stable -project chef

      - name: Setup Docker Desktop
        uses: docker/setup-buildx-action@v3

      - name: Test Kitchen Windows
        shell: bash
        run: |
          export CHEF_LICENSE=accept-no-persist
          bundle exec kitchen test ${{ matrix.scenario }}-${{ matrix.os }}
        env:
          CHEF_LICENSE: accept-no-persist
