name             'hbase'
maintainer       'Thomas Vincent'
maintainer_email 'thomasvincent@github.com'
license          'Apache-2.0'
description      'Installs/Configures Apache HBase'
version          '1.2.0'
chef_version     '>= 18.0'

supports 'ubuntu',    '>= 20.04'
supports 'debian',    '>= 11.0'
supports 'redhat',    '>= 8.0'
supports 'centos',    '>= 8.0'
supports 'rocky',     '>= 8.0'
supports 'almalinux', '>= 8.0'
supports 'oracle',    '>= 8.0'
supports 'amazon',    '>= 2023.0'

depends 'ark', '~> 5.0'

issues_url 'https://github.com/somethingwithproof/chef-cookbooks/issues'
source_url 'https://github.com/somethingwithproof/chef-cookbooks/tree/main/cookbooks/hbase'
