source 'https://rubygems.org'

gem 'chef', '~> 19.2'
gem 'chef-cli', '~> 6.1'

# Pin psych to avoid compilation issues with Ruby 3.2+
gem 'psych', '< 6'

group :development do
  gem 'chefspec', '~> 9.3'
  gem 'cookstyle', '~> 8.6'
  gem 'kitchen-dokken', '~> 2.22'
  gem 'kitchen-inspec'
  gem 'test-kitchen', '>= 3.0'
end
