source 'https://rubygems.org'

gem 'chef', '>= 18.0'
gem 'cookstyle', '~> 7.32'
gem 'chefspec', '~> 9.3'
gem 'test-kitchen', '~> 3.5'
gem 'kitchen-dokken', '~> 2.18'  # Preferred over kitchen-docker which lacks maintenance
gem 'kitchen-inspec', '~> 2.6'
gem 'inspec', '~> 5.21'
gem 'rack', '>= 2.2.22'
gem 'rexml', '>= 3.4.2'
gem 'faraday', '>= 1.10.5'
