name 'snmp'
maintainer 'Thomas Vincent'
maintainer_email 'thomasvincent@gmail.com'
license 'Apache-2.0'
description 'Installs/Configures snmp on redhat, centos, ubuntu, debian'
version '5.0.0'
chef_version '>= 18.0', '< 20.0'

supports 'ubuntu', '>= 20.04'
supports 'debian', '>= 11.0'
supports 'centos', '>= 8'
supports 'redhat', '>= 8'
supports 'scientific', '>= 8'
supports 'fedora', '>= 34'
supports 'amazon', '>= 2'
supports 'suse', '>= 15'

source_url 'https://github.com/thomasvincent/chef-snmp-cookbook'
issues_url 'https://github.com/thomasvincent/chef-snmp-cookbook/issues'