name 'snmp'
maintainer 'Thomas Vincent'
maintainer_email 'thomasvincent@gmail.com'
license 'Apache-2.0'
description 'Installs/Configures snmp on redhat, centos, ubuntu, debian'
version '5.0.0'
chef_version '>= 18.0'

source_url 'https://github.com/somethingwithproof/chef-cookbooks/tree/main/cookbooks/snmp'
issues_url 'https://github.com/somethingwithproof/chef-cookbooks/issues'

supports 'ubuntu', '>= 20.04'
supports 'debian', '>= 11.0'
supports 'redhat', '>= 8.0'
supports 'centos', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'almalinux', '>= 8.0'
supports 'oracle', '>= 8.0'
supports 'amazon', '>= 2023.0'