require 'cookstyle'
require 'rubocop/rake_task'
require 'rspec/core/rake_task'

# Style tests. Rubocop
desc 'Run Ruby style checks'
RuboCop::RakeTask.new(:style) do |task|
  task.options << '--display-cop-names'
end

# Spec tests
desc 'Run ChefSpec unit tests'
RSpec::Core::RakeTask.new(:spec) do |task|
  task.rspec_opts = '--color --format documentation'
end

# Integration tests. Kitchen.ci
namespace :integration do
  desc 'Run Test Kitchen with Vagrant'
  task :vagrant do
    sh 'kitchen test'
  end

  desc 'Run Test Kitchen with Docker'
  task :docker do
    sh 'KITCHEN_LOCAL_YAML=.kitchen.docker.yml kitchen test'
  end
end

# Default
task default: %w(style spec)
