name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Ruby
        uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Run Cookstyle
        run: bundle exec cookstyle

      - name: Run ChefSpec
        run: bundle exec rspec

      - name: Run Kitchen Test
        run: bundle exec kitchen test
        env:
          CHEF_LICENSE: accept-no-persist
