name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Ruby
        uses: ruby/setup-ruby@6ca151fd1bfcfd6fe0c4eb6837eb0584d0134a0c
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Run Cookstyle
        run: bundle exec cookstyle

      - name: Run ChefSpec
        run: bundle exec rspec

      - name: Run Kitchen Test
        run: bundle exec kitchen test
        env:
          CHEF_LICENSE: accept-no-persist
