---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

env:
  CHEF_LICENSE: accept-no-persist

jobs:
  lint:
    name: Cookstyle Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Ruby
        uses: ruby/setup-ruby@6ca151fd1bfcfd6fe0c4eb6837eb0584d0134a0c # v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Run Cookstyle
        run: bundle exec cookstyle

  unit-test:
    name: Unit Tests
    runs-on: [self-hosted]
    timeout-minutes: 15
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Ruby
        uses: ruby/setup-ruby@6ca151fd1bfcfd6fe0c4eb6837eb0584d0134a0c # v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Run ChefSpec tests
        run: bundle exec rspec
