repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(json|yaml|yml|md)$

  - repo: local
    hooks:
      - id: cookstyle
        name: cookstyle
        entry: bundle exec cookstyle
        language: system
        files: \.(rb)$
        pass_filenames: false

      - id: rspec
        name: rspec
        entry: bundle exec rspec
        language: system
        pass_filenames: false
        stages: [pre-push]
