source 'https://rubygems.org'

gem 'chef', '~> 19.1'
gem 'chefspec'
gem 'inspec'
gem 'kitchen-docker'
gem 'kitchen-inspec'
gem 'cookstyle', require: false
gem 'fauxhai-ng'
gem 'test-kitchen'
gem 'rake'

# Required for Ruby 3.4+ compatibility (local development)
gem 'syslog', '~> 0.4.0'
