source 'https://rubygems.org'

group :development, :test do
  gem 'chefspec'
  gem 'cookstyle'
  gem 'fauxhai-ng'
  gem 'inspec'
  gem 'kitchen-dokken'
  gem 'kitchen-inspec'
  gem 'rake'
  gem 'syslog', '~> 0.1.2' # Required for Ruby 3.4+ compatibility
  gem 'test-kitchen'
end
